language: bash

sudo: required

services:
  - docker

install:
  - docker-compose -f ./docker-compose-travis.yml -p tests up -d 

before_script:
  - docker exec -i tests_erlang_1 sh -c "sed -i '/auth.mysql.server/c auth.mysql.server = mysql_server:3306' /emqx_auth_mysql/etc/emqx_auth_mysql.conf"
  - docker exec -i tests_erlang_1 sh -c "echo 'auth.mysql.username = root' >> /emqx_auth_mysql/etc/emqx_auth_mysql.conf "
  - docker exec -i tests_erlang_1 sh -c "echo 'auth.mysql.password = public' >> /emqx_auth_mysql/etc/emqx_auth_mysql.conf"

script:
  - docker exec -i tests_erlang_1 sh -c "make -C /emqx_auth_mysql compile"
  - docker exec -i tests_erlang_1 sh -c "make -C /emqx_auth_mysql eunit"
  - docker exec -i tests_erlang_1 sh -c "make -C /emqx_auth_mysql ct"

after_script:
  - docker-compose -f ./docker-compose-travis.yml -p tests down 
