language: bash

sudo: required

services:
  - docker

install:
  - docker-compose -f ./docker-compose-travis.yml -p tests up -d 

before_script:
  - while [[ ! -z $(docker ps -a -f name=tests_mysql_client_1 -f status=running -q) ]]; do echo "wait mysql server" && sleep 1; done
  - docker exec -i $(docker ps -a -f name=tests_erlang_1 -q) sh -c "sed -i '/auth.mysql.server/c auth.mysql.server = mysql_server:3306' /emqx_auth_mysql/etc/emqx_auth_mysql.conf"
  - docker exec -i $(docker ps -a -f name=tests_erlang_1 -q) sh -c "echo 'auth.mysql.username = root' >> /emqx_auth_mysql/etc/emqx_auth_mysql.conf "
  - docker exec -i $(docker ps -a -f name=tests_erlang_1 -q) sh -c "echo 'auth.mysql.password = public' >> /emqx_auth_mysql/etc/emqx_auth_mysql.conf"

script:
  - docker exec -i $(docker ps -a -f name=tests_erlang_1 -q) sh -c "make -C /emqx_auth_mysql compile"
  - docker exec -i $(docker ps -a -f name=tests_erlang_1 -q) sh -c "make -C /emqx_auth_mysql eunit"
  - docker exec -i $(docker ps -a -f name=tests_erlang_1 -q) sh -c "make -C /emqx_auth_mysql ct"

after_script:
  - docker-compose -f ./docker-compose-travis.yml -p tests down 
