version: '3'

services:
  erlang:
    image: erlang:21.3
    labels: 
      name: tests
    volumes:
      - ./:/emqx_auth_mysql
    networks:
      - emqx-bridge
    depends_on:
      - mysql_server
    tty: true

  mysql_server:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: public 
      MYSQL_DATABASE: mqtt
    networks:
      - emqx-bridge
    command: --bind-address 0.0.0.0

  mysql_client:
    image: mysql:5.7
    networks:
      - emqx-bridge
    depends_on:
      - mysql_server
    volumes:
      - ./mqtt.sql:/emqx_auth_mysql_test.sql
    command:
      - /bin/bash
      - -c
      - |
        service mysql start
        echo "show tables;" | mysql -h mysql_server -u root -ppublic mqtt
        while [[ $$? -ne 0 ]];do echo "show tables;" | mysql -h mysql_server -u root -ppublic mqtt; done
        mysql -h mysql_server -u root -ppublic mqtt</emqx_auth_mysql_test.sql
        echo "------------show tables------------"
        echo "show tables;" | mysql -h mysql_server -u root -ppublic mqtt

networks:
  emqx-bridge:
    driver: bridge